import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTableClan1710916127576 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        CREATE TABLE "clan" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "name" VARCHAR(255),
            "information" VARCHAR(255),
            "image" JSONB,
            "rule" VARCHAR(255),
            "created_by" BIGINT,
            "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            "deleted_at" TIMESTAMP DEFAULT NULL
            );
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS clan');
  }
}
