import { MigrationInterface, QueryRunner } from 'typeorm';

export class MemberEvent1710924049099 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        CREATE TABLE "member" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "clan_id" BIGINT,
            "user_id" BIGINT,
            "role_cd" INT,
            "created_by" BIGINT,
            "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            "deleted_at" TIMESTAMP DEFAULT NULL
            );
        `);

    await queryRunner.query(`
      CREATE TABLE "event" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "clan_id" BIGINT NOT NULL,
        "content" VARCHAR(255) ,
        "image" JSONB,
        "time_event" TIMESTAMP ,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        "deleted_at" TIMESTAMP DEFAULT NULL
      );
    `);

    await queryRunner.query(`
      CREATE TABLE "event_comment" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "event_id" BIGINT NOT NULL,
        "image" JSONB,
        "content" VARCHAR(255),
        "created_by" BIGINT,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        "deleted_at" TIMESTAMP DEFAULT NULL
      );
    `);

    await queryRunner.query(`
        CREATE TABLE "notifications" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "type" SMALLINT,
          "content" TEXT NOT NULL,
          "reference_id" BIGINT NOT NULL,
          "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
          "updated_at" TIMESTAMP DEFAULT NULL,
          "deleted_at" TIMESTAMP DEFAULT NULL
        );
      `);

    await queryRunner.query(`
      CREATE TABLE "recipients" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" BIGINT NOT NULL,
        "notifications_id" BIGINT NOT NULL,
        "status_cd" SMALLINT DEFAULT 0,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        "updated_at" TIMESTAMP DEFAULT NULL,
        "deleted_at" TIMESTAMP DEFAULT NULL
      );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXIST member');
    await queryRunner.query('DROP TABLE IF EXIST event');
    await queryRunner.query('DROP TABLE IF EXISTS event_comment');
    await queryRunner.query('DROP TABLE IF EXISTS  notifications');
    await queryRunner.query('DROP TABLE IF EXISTS  recipients');
  }
}
