export class AppConstant {
  public static PUBLISH_OPTION_ALL = 0;
  public static PUBLISH_OPTION_SHARE = 1;
  public static STATUS_NOT_ANSWERED = 0;
  public static STATUS_ANSWERED = 1;
  public static STATUS_CONFIRMED = 2;
  public static STATUS_COMPLETED = 3;
  public static TYPE_QUERY_STRING = 0;
  public static TYPE_QUERY_JSON = 1;
  public static TAG_REFERENCE_TYPE_DOCUMENT = 1;
  public static TAG_REFERENCE_TYPE_QUESTION = 2;
  public static TAG_REFERENCE_TYPE_FEEDBACK = 3;
  public static ROLE_OWNER = 1;
  public static ROLE_ADMIN = 2;
  public static ROLE_LABORER = 3;
  public static FOLDER_UPLOAD_FILE = 'files';
  public static FOLDER_UPLOAD_IMAGE = 'images';
  public static OPERATION_IN = 'in';
  public static OPERATION_NOT_IN = 'nin';
  public static OPERATION_EQ = 'equal';
  public static TYPE_DOCUMENT = 1;
  public static TYPE_QUESTION = 2;
  public static TYPE_FEEDBACK = 3;
  public static FORMAT_DATE = 'YYYY/MM/DD';
  public static STEM_DEFAULT = 3;
  public static YEAR_CIRCLE_LENGTH = 60; //month
  public static SHEET_TITLE_DEFAULT = 'シート1';
  public static AREA_TITLE_DEFAULT = 'エリア';
  public static CIRCLE_TITLE_DEFAULT = '播種';
  public static UNIT_CONVERSION = 100;
  public static PLANTING_DENSITY = 10;
  public static FORMAT_DATE_MONTH_YEAR = 'YYYY/MM';
  public static AREA_QUANTITY_DEFAULT = 4;
  public static NO_LOGIN = 0;
  public static LOGGED = 1;
  public static SPLIT_CHARACTERS = /[。？！．.!?]/;
  public static SPECIFIC_WORK_CONTRACT = 0;
  public static WORK_CONTRACT = 0;
  public static MISCELLANEOUS_INCOME = 0;
  public static SUBSIDY_INCOME_DEFAULT = 750000;
  public static RAGE_SUMMER_MONTH = { startMonthSummer: 7, endMonthSummer: 9 };
  public static ADDITION_DAY_SUMMER = 15;
  public static MINUS_DAY_SUMMER = 40;
  public static ADDITION_HOURS_SUMMER = 6;
  public static AREA_RATE_CONSUMPTION_VOLUME = 1000; // L/1000m2
  public static NUMBER_YEAR_CALCULATOR_NEW_BUILDINGS = 14; //year
  public static NUMBER_YEAR_CALCULATOR_USED_BUILDINGS = 10; //year
  public static NUMBER_YEAR_CALCULATOR_NEW_MECHANICAL_EQUIPMENT = 7; //year
  public static NUMBER_YEAR_CALCULATOR_USED_MECHANICAL_EQUIPMENT = 5; //year
  public static CONSULTING_LABOR_COST_DEFAULT = 0; // 栽培技術コンサル人件費
  public static EQUIPMENT_REPAIR_DEFAULT = 10000; // 設備修繕費
  public static TOOLS_COST_DEFAULT = 10000; // 農具費
  public static MATERIAL_COSTS_DEFAULT = 25; // 諸材料費
  public static WORK_CLOTHING_COSTS_DEFAULT = 10000; // 作業用衣料費
  public static MISCELLANEOUS_EXPENSES_COSTS_DEFAULT = 10000; // 雑費（予備費）
  public static TITLE_COPY_SHEET = 'のコピー';
  public static SHIPPING_FEE_DEFAULT = 0; // 出荷手数料（JA等）
  public static PROMOTIONAL_COSTS_DEFAULT = 0; // 販促活動費
  public static PACKING_MATERIAL_DEFAULT = 0; // 梱包材料費
  public static LOGISTICS_COSTS_DEFAULT = 0; // 物流・輸送費
  public static OTHER_SALES_COSTS_DEFAULT = 0; // その他販売経費
  public static SHEET_NOT_STAR = 0;
  public static SHEET_STAR = 1;
  public static LIST_MONTH_HAS_TAX = [15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60];
  public static NUMBER_GROUND_RENT = 20000; // 20,000円
  public static OFFICE_PERSONNEL_COSTS_DEFAULT = 0; // 本社人件費
  public static INSURANCE_SUPPORT_COSTS_DEFAULT = 10000; // 農業共済掛金（保険）
  public static ASSOCIATION_FEES_DEFAULT = 50000; // 組合費等（水利組合等）
  public static OTHER_ADMINISTRATIVE_EXPENSES = 0; // その他管理諸費
  public static ONCE_EVERY_ONE_YEAR = 12; // months
  public static NUMBER_YEAR_CIRCLE_PLAN = 5; // year
  public static UNIT_CONVERSION_A = 10;
  public static BUSINESS_PLAN_RESULT_CSV = 'business-plan-result.csv';
  public static BUSINESS_PLAN_RESULT_PDF = 'business-plan-result.pdf';
  public static TREE_QUANTITY_CALCULATOR = 4500;
  public static NOTIFICATION_TYPE_QUESTION = 1;
  public static NOTIFICATION_TYPE_QUESTION_COMMENT = 2;
  public static NOTIFICATION_TYPE_DOCUMENT = 3;
  public static NOTIFICATION_TYPE_FEEDBACK = 4;
  public static NOTIFICATION_TYPE_BUSINESS_PLAN = 5;
  public static NOTIFICATION_TYPE_BUSINESS_PLAN_COMMENT = 6;
  public static NOTIFICATION_TYPE_SCHEDULE_COMMENT = 7;
  public static STATUS_NOTIFICATION_UNREAD = 0;
  public static STATUS_NOTIFICATION_READ = 1;
  public static DESC = 'DESC';
  public static ASC = 'ASC';
  public static LOGIN_NOT_REMEMBER = 0;
  public static LOGIN_REMEMBER = 1;
}
